# **1. Set**
- 수학의 **집합**과 비슷한 형태로 순서가 없기 때문에 **어떤 값이 먼저 나올지 알 수 없고**, **중복되는 데이터를 허용하지 않음**
- 딕셔너리처럼 중괄호를 사용해서 선언하지만 **key는 존재하지 않고 value만 존재**

### 1-1. set만들기

In [ ]:
#값을 넣으며 만들기
set1 = {1,3,5,7}
print(type(set1))
#리스트를 이용해서 만들기
set2 = set([11,22,33,44])
print(type(set2))
print(set2) # 순서는 신경쓰기 말기!
#중복은 허용하지 않는다.
set3 = {1, 3, 5, 7, 9, 1, 2, 3, 4, 5, 7, 8, 10, 6, 3, 5, 9, 1, 3}
print(set3)

<class 'set'>
<class 'set'>
{33, 11, 44, 22}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
# 리스트의 중복 제거를 할 때 유용하게 사용할 수 있다.
numbers = [10, 20, 30, 40, 10, 20, 40, 50, 60, 20, 10, 30, 70, 80, 90]
print(numbers)
numbers =sorted(list(set(numbers)))
print(numbers)

[10, 20, 30, 40, 10, 20, 40, 50, 60, 20, 10, 30, 70, 80, 90]
[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
print(20 in numbers)

True

### 1-2. **set함수**

In [ ]:
# add() : set에 단일 데이터 추가
set1 = {22, 33}
set1.add(11)
print(set1)

# update() : set에 여러 데이터를 한 번 에 추가
set2 = {10, 20, 30}
# set2.update({66, 20, 77, 88}) # set 전달
# set2.update([66, 20, 77, 88]) # list 전달
set2.update((66, 20, 77, 88)) # tuple 전달
print(set2)

# remove() : set의 데이터를 제거, 제거할 데이터가 없으면 에러!
set2.remove(66)
print(set2)
# set2.remove(100) # 에러!

# discard() : set의 데이터를 제거, 제거할 데이터가 없어도 아무일도 일어나지 않는다.
set2.discard(30)
print(set2)
set2.discard(30)
print(set2)

{33, 11, 22}
{66, 10, 77, 20, 88, 30}
{10, 77, 20, 88, 30}
{10, 77, 20, 88}

### 1-3. set의 연산자

In [ ]:
nums1 = {11,22,33,44,55}
nums2 = {33,44,55,66,77}

#합집합
res = nums1 | nums2
print(res)
res = nums1.union(nums2)
print(res)

#교집합
res = nums1 & nums2
print(res)
res = nums1.intersection(nums2)
print(res)

#차집합
res = nums1 - nums2
print(res)
res = nums1.difference(nums2)
print(res)
# 대칭 차집합
res = nums1 ^ nums2
print(res)
res = nums1.symmetric_difference(nums2)
print(res)

{33, 66, 11, 44, 77, 22, 55}
{33, 66, 11, 44, 77, 22, 55}
{33, 44, 55}
{33, 44, 55}
{11, 22}
{11, 22}
{66, 22, 11, 77}
{66, 22, 11, 77}